### ISSUE TITLE
Check if port 402 must be public

### ISSUE THREAD

**Issue by Munsio** [CausticLab/rancher-catalog#6]
We use the acmetool with the well-known directive so i think that port 402 shouldn't be public cause it is an rancher internal proxy with nginx

**Comment by emcniece** [comment]
From https://github.com/Munsio/docker-letsencrypt-nginx-proxy-companion/issues/13#issuecomment-299822855 (I think)

Can we proxy :80/:443 to :402 in the `acmetool` upstream?

**Comment by Munsio** [comment]
Sure its the same with rgon.port where we can route to an containers port without opening it to the outside. We can hardcode it, its nothing which should be touched by endusers, but we shouldnt forget to change the nginx.tmpl file
